name: Frontend CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main 

      - name: Déploiement sur le VPS
        if: success() && github.ref == 'refs/heads/maine'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PORTABLE }}
          script: |
            yes |docker system prune
            cd docker
            sudo rm -r lecerfdesign-front
            git clone git@github.com:Killianlecorf/lecerfdesign-front.git
            cd lecerfdesign-front/lecerfdesign
            sudo docker compose up --build -d
            cd ../api
            sudo docker compose up --build -d

